### ISSUE TITLE
NBA Issue

### ISSUE THREAD

**Issue by omar319** [andrewderango/NHL-Game-Probabilities#7] opened 2023-12-09 15:17 UTC
Hey,

it appears there's an issue with running NBA  

there is also an error with NBA

```
Traceback (most recent call last):
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 559, in <module>
    main()
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 553, in main
    date, today_games_df = get_todays_games(param, team_list, games_metadf)
  File "./NHL-Game-Probabilities/NBA/nba_game_probability_model.py", line 285, in get_todays_games
    today_games_df['Home Win Prob'] = today_games_df.apply(lambda row: f"{calc_prob(team_name_obj_dict[row['Home Team']], team_name_obj_dict[row['Visiting Team']], param)*100:.2f}%", axis=1)
  File "/mnt/f/repositories/virtualenvs/nhl-nba-game-probabilities/lib/python3.10/site-packages/pandas/core/frame.py", line 4081, in __setitem__
    self._set_item_frame_value(key, value)
  File "./lib/python3.10/site-packages/pandas/core/frame.py", line 4209, in _set_item_frame_value
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

**Comment by omar319** [comment] 2023-12-09 15:18
It also doesn't seem to be picking up today's NHL games

**Comment by andrewderango** [comment] 2023-12-10 01:43
The NBA error should be fixed. Note that it will say that there are no games today. This is because the Pacers vs Lakers NBA Cup finals game does not count towards regular season standings and is therefore not considered to be a game in the NBA season. In case you were curious, we have the Pacers at a 57% chance of winning. The projected point differential is 2.0 points.

As for the NHL error, I can't seem to reproduce the error that you're receiving. I received the following output:

```
        GameID Game State            Home Team Home Goals Away Goals             Away Team Pre-Game Home Win Probability Pre-Game Away Win Probability Home Record Away Record
1   2023020408      Final        Boston Bruins          5          3       Arizona Coyotes                        53.14%                        46.86%      18-5-3     13-11-2
2   2023020409      Final       Calgary Flames          2          4     New Jersey Devils                        44.96%                        55.04%     11-13-3     14-10-1
3   2023020410      Final         Dallas Stars          1          6  Vegas Golden Knights                        41.63%                        58.37%      15-8-3      18-5-5
4   2023020411   Period 2       Buffalo Sabres          0          2    Montréal Canadiens                        53.32%                        46.68%     11-14-2     11-12-3
5   2023020412   Period 2    Detroit Red Wings          1          2       Ottawa Senators                        56.30%                        43.70%      14-7-4     10-11-0
6   2023020413   Period 2  Toronto Maple Leafs          1          0   Nashville Predators                        50.92%                        49.08%      13-6-4     14-12-0
7   2023020414   Period 2  Washington Capitals          4          0      New York Rangers                        29.60%                        70.40%      12-8-3      18-5-1
8   2023020415   Period 2   New York Islanders          0          0     Los Angeles Kings                        21.25%                        78.75%      11-7-7      16-4-3
9   2023020416   Period 1   Chicago Blackhawks          2          0       St. Louis Blues                        38.01%                        61.99%      8-16-1     13-12-1
10  2023020417   Period 1   Colorado Avalanche          0          0   Philadelphia Flyers                        52.12%                        47.88%      16-8-2     14-10-2
11  2023020418   Pre-Game       Seattle Kraken          0          0   Tampa Bay Lightning                        42.39%                        57.61%      8-13-6     12-11-5
12  2023020419   Pre-Game    Vancouver Canucks          0          0   Carolina Hurricanes                        67.71%                        32.29%      17-9-1     14-11-1
```

**Closed as completed** 2023-12-15 18:56 UTC

**Comment by Elsberry6769** [comment] 2024-10-30 19:54
I am having the same issue - mismatched columns.  The error occurs on line 144 :    scraped_df.loc[len(scraped_df)] = row

I've ran it both in VS code and PyCharm and the error is present in both environments.

**Comment by andrewderango** [comment] 2024-10-31 00:05
Thanks for pointing that out. Seems like BasketballReference added a new field to their table which caused the scraping script to throw an error. 

Nonetheless, should be fixed now. Also updated the script to work for 24/25 season. Let me know if you have any issues.
